const fs = require('fs')
const path = require('path')
const ess = require('../generated/essentialWithEcommerceAdded.json')

Object.keys(ess).forEach(propName => {
    const keyVal = ess[propName].propJson
    let prop = '#Generated by an angel\n'
    Object.keys(keyVal).forEach(key => {
        const val = keyVal[key]
        prop += `${key}=${val}\n`
    })
    fs.writeFileSync(
        path.join(__dirname, `../generated/props/${propName}`),
        // `../generated/props/${propName}`,
        prop,
        'utf-8'
    )
})