module.exports = {
    langs: ['fr_FR', 'de_DE', 'it_IT'],
    cssSeparator: '§',
    keysToExtract: 
`
account > account.addressbook.addresslist.create
account > account.addressbook.addresslist.header
account > account.addressbook.miniaddress.phone
account > account.header
account > account.header.creataccount
account > account.login.checkmessage
account > account.login.logininclude.customersheader
account > account.login.logininclude.forgotpassword
account > account.login.logininclude.forgotpassword.label
account > account.login.logininclude.locked
account > account.login.logininclude.loginerror
account > account.login.logininclude.loginfberror
account > account.login.logininclude.oauthcustomersheader
account > account.login.logininclude.oauthcustomersheaderreturning
account > account.login.logininclude.registered
account > account.login.orderbutton
account > account.login.ordererror
account > account.login.orderheader
account > account.orderdetails.returnorder
account > account.orderdetails.returnshopping
account > account.orders.datelabel
account > account.orders.items
account > account.orders.noorders
account > account.orders.notfound
account > account.orders.numberlabel
account > account.orders.orderdetail
account > account.orders.orderhistory
account > account.orders.shippedto
account > account.orderstatusinclude.ordercanceled
account > account.orderstatusinclude.ordercontact
account > account.orderstatusinclude.orderprocessed
account > account.orderstatusinclude.ordershipped
account > account.orderstatusinclude.statuslabel
account > account.passwordchangedemail.dear
account > account.passwordchangedemail.message1
account > account.passwordchangedemail.message2
account > account.passwordchangedemail.message3
account > account.passwordchangedemail.subject
account > account.passwordreset.button
account > account.passwordreset.message
account > account.passwordreset.notfounderror
account > account.passwordreset.resubmit
account > account.passwordreset.sent
account > account.passwordreset.title
account > account.passwordreset.title2
account > account.passwordresetconfirm.homepagelink
account > account.passwordresetconfirm.message
account > account.passwordresetconfirm.title
account > account.paymentinstrumentdetails.expires
account > account.paymentinstrumentlist.addcard
account > account.paymentinstrumentlist.addcard.label
account > account.paymentinstrumentlist.header
account > account.setnewpassword.title
account > account.setnewpasswordconfirm.title
account > account.setnewpasswordconfirm.message
account > account.user.registration.createnew
account > account.user.registration.editaccount
account > account.user.registration.editname
account > account.user.registration.logininfo
account > account.user.registration.name
account > wishlist.addaddress
checkout > approachingpromo.purchase
checkout > approachingpromo.receive
checkout > billing.addressheader
checkout > billing.creditcarddeleteconfirm
checkout > billing.creditcarddeleted
checkout > billing.creditcarddeletenotselected
checkout > billing.creditcardexpires
checkout > billing.creditcardlistexp
checkout > billing.creditcardlistnocards
checkout > billing.creditcardlistselect
checkout > billing.creditcardloaderror
checkout > billing.creditcardnotdeleted
checkout > billing.deletecard
checkout > billing.missingprocessorerror
checkout > billing.newcreditcardadded
checkout > billing.ownerparseerror
checkout > billing.paymentheader
checkout > billing.selectcreditcard
checkout > billing.zerobalance
checkout > cart.bonusnumselected
checkout > cart.bonusproduct.button.more
checkout > cart.cartcouponinvalid
checkout > cart.cartempty
checkout > cart.carterror
checkout > cart.COUPON_CODE_MISSING
checkout > cart.COUPON_CODE_UNKNOWN
checkout > cart.couponcode
checkout > cart.entercouponcode
checkout > cart.itemtotal
checkout > cart.lastvisited.header
checkout > cart.limitedQuantity
checkout > cart.NO_ACTIVE_PROMOTION
checkout > cart.option
checkout > cart.store.deliveryoptions
checkout > cart.store.homedelivery
checkout > cart.store.instorepickup
checkout > cart.store.notavailable
checkout > cart.store.storepickupaddress
checkout > cart.taxinvalid
checkout > cart.unableToAdd
checkout > checkoutlogin.checkoutguestbutton
checkout > checkoutlogin.guestheader
checkout > checkoutlogin.guestmessage
checkout > checkoutlogin.guesttitle
checkout > checkoutlogin.registerbenefits
checkout > checkoutprogressindicator.billing
checkout > checkoutprogressindicator.placeorder
checkout > checkoutprogressindicator.shipping
checkout > checkoutprogressindicator.shippingmethods
checkout > checkoutprogressindicator.step1
checkout > checkoutprogressindicator.step2
checkout > checkoutprogressindicator.step3
checkout > checkoutprogressindicator.step4
checkout > confirm.error.declined
checkout > confirm.error.technical
checkout > confirmation.message
checkout > confirmation.returnshop
checkout > confirmation.thankyou
checkout > minibillinginfo.amount
checkout > minibillinginfo.billingaddress
checkout > minicart.directcheckout
checkout > minicart.title
checkout > minicart.viewcart
checkout > minicart.viewcart.label
checkout > minishipments.shippingaddress
checkout > multishippingshipments.shipment
checkout > singleshipping.enteraddress
checkout > singleshipping.phonerequired
checkout > summary.applied
checkout > summary.couponnumber
checkout > summary.editcart
checkout > summary.notapplied
checkout > summary.orderdiscount
checkout > summary.ordertotal
checkout > summary.title
common > error_forbidden.message
components > menulinksleft.ecommerce
components > menulinksright.promotions
components > orderdetails.billingaddress
components > orderdetails.paymentmethod
components > orderdetails.paymenttotal
components > orderdetails.shippingaddress
components > orderdetails.shippingdetails
components > orderdetails.shippingmethod
components > orderdetails.shippingstatus
components > orderdetails.shippingto
components > orderdetails.tracking
components > ordersummary.orderdiscount
components > ordersummary.ordershipping
components > ordersummary.ordersubtotal
components > ordersummary.subtotal
contact > contact.accessories.label
email > contactus.other
email > contactus.sav
email > contactus.subject.accessories
email > contactus.subject.notice
email > contactus.text
email > orderconfirmation.altorderconfirmed
email > orderconfirmation.azur
email > orderconfirmation.contactus
email > orderconfirmation.generatedmail
email > orderconfirmation.paymentinfos
email > orderconfirmation.preheader
email > orderconfirmation.shippingcost
email > orderconfirmation.subject
email > orderconfirmation.tel
email > orderconfirmation.thankfororder
email > orderconfirmation.thankfororder2
email > passwordemail.corpsmessage
email > passwordemail.forgottenpassword
email > passwordemail.nolink1
email > passwordemail.nolink2
email > passwordemail.oupsforgottenpassword
email > passwordemail.resetpassword
email > passwordemail.subject
email > resource.dear
email > resource.from
email > resource.passwordassistance
email > welcoming.confirmation
email > welcoming.easierpurchase
email > welcoming.espaceperso
email > welcoming.history
email > welcoming.logo.alt
email > welcoming.noreply
email > welcoming.receiveoffer
email > welcoming.subject
email > welcoming.thank
email > welcoming.univers
forms > address.phone.example
forms > address.postalcode.example
forms > billing.email
forms > checkout.addtoaddressbook
forms > checkout.addtoemaillist
forms > checkout.addtoemaillistParis
forms > checkout.shipment.no
forms > checkout.shipment.yes
forms > checkout.useasbillingaddress
forms > confirm.delete
forms > contactus.ambassador.submit
forms > contactus.ambassador.undertitle
forms > contactus.city
forms > country.luxembourg
forms > country.netherlands
forms > country.nl
forms > creditcard.cvnlabel
forms > creditcard.cvnmissingerror
forms > creditcard.cvnrangeerror
forms > creditcard.monthmissingerror
forms > creditcard.numberexample
forms > creditcard.numbermissingerror
forms > creditcard.numberrangeerror
forms > creditcard.numbervalueerror
forms > creditcard.ownerlabel
forms > creditcard.savecard
forms > creditcard.type
forms > creditcard.typemissing
forms > creditcard.yearmissingerror
forms > creditcard.yearvalueerror
forms > forms.productreview.author
forms > forms.productreview.author.missing-error
forms > forms.productreview.comment
forms > forms.productreview.comment.missing-error
forms > forms.productreview.email
forms > forms.productreview.email.missing-error
forms > forms.productreview.rating
forms > forms.productreview.rating.yourreview
forms > giftcert.purchase.from.label
forms > global.createnowbutton
forms > label.newpassword
forms > label.password
forms > label.username
forms > login.rememberme
forms > ordertrack.orderEmail
forms > ordertrack.orderEmail.missing-error
forms > ordertrack.orderNumber
forms > ordertrack.orderNumber.missing-error
forms > ordertrack.postalCode
forms > paymentMethodType.label
forms > profile.confirmemail
forms > profile.dob
forms > profile.email
forms > profile.firstname
forms > profile.lastname
forms > profile.newpassword
forms > profile.newpasswordconfirm
forms > profile.passwordconfirm
forms > profile.passwordnomatch
forms > profile.phone
forms > promotions.address
forms > promotions.civility
forms > promotions.contact
forms > promotions.enteraddress
forms > promotions.giftproduct
forms > promotions.incorrectiban
forms > promotions.mr
forms > promotions.mrs
forms > promotions.productbought
forms > promotions.promotion
forms > promotions.purchasedate
forms > promotions.purchaseinfo
forms > promotions.receipt
forms > promotions.store
forms > promotions.street
forms > promotions.street_number
forms > promotions.submit
forms > promotions.subscribe
forms > promotions.terms
forms > resource.8_255characters
forms > resource.address1
forms > resource.address2
forms > resource.addtocart
forms > resource.city
forms > resource.country
forms > resource.postalcode
forms > resource.postalCode_city
forms > resource.send
forms > resource.zipcode
forms > resource.zippostalcode
forms > restriction.country
forms > subscribe.email.default
forms > summary.cgvacceptance
forms > title.address
forms > title.creditcard
locale > global.accountlink
locale > global.addtocart
locale > global.allnotavailable
locale > global.amount
locale > global.applied
locale > global.apply
locale > global.availability
locale > global.carousel.featuredproducts
locale > global.checkout
locale > global.continue
locale > global.continuebilling
locale > global.continuecheckout
locale > global.continueplaceorder
locale > global.continueshippingmethods
locale > global.continueshopping
locale > global.createbutton
locale > global.createnowbutton
locale > global.delete
locale > global.description
locale > global.details
locale > global.edit
locale > global.editaaddress
locale > global.editdetails
locale > global.error
locale > global.estimatedtotal
locale > global.find
locale > global.folderrefinement.label.prefix
locale > global.free
locale > global.from
locale > global.go
locale > global.goprevious
locale > global.header.wishlistlink
locale > global.instock
locale > global.invalidphone
locale > global.invalidpostal
locale > global.item
locale > global.itemno
locale > global.login
locale > global.logout
locale > global.next
locale > global.nosavedaddress
locale > global.nothanks
locale > global.or
locale > global.ordertotal
locale > global.paginginformation.showing
locale > global.price
locale > global.privacypolicy
locale > global.product
locale > global.qty
locale > global.quantity
locale > global.register
locale > global.remove
locale > global.search
locale > global.select
locale > global.selectaddressmessage
locale > global.signup
locale > global.socialshare.whatsapp.label
locale > global.submitorder
locale > global.totalprice
locale > global.updatecart
locale > global.user
locale > globalaccount.createheader
locale > globalaccount.createmessage
order > order.orderconfirmation-email.thankyouus
order > order.orderdetails.billingaddress
order > order.orderdetails.giftcertfrom
order > order.orderdetails.giftcertshippingaddress
order > order.orderdetails.giftcertto
order > order.orderdetails.giftmessage
order > order.orderdetails.notshipped
order > order.orderdetails.ordernumber
order > order.orderdetails.orderplaced
order > order.orderdetails.paymentinfo
order > order.orderdetails.paymentmethod
order > order.orderdetails.paymenttotal
order > order.orderdetails.shippingmethod
order > order.orderdetails.shippingstatus
order > order.orderdetails.shippingto
order > order.ordersummary.orderdiscount
order > order.ordersummary.ordershipping
order > order.ordersummary.subtotal
product > product.bonusproductalert
product > product.buy.here
product > product.comparator.title
product > product.label
product > product.profiter
product > writereviewdialog.confirmation
storelocator > storelocator.countryRestriction
storelocator > storelocator.ou
storelocator > storelocator.storelocatorresults.ensavoirplus
`    
}